import { NavHeader } from '@/components/nav-header';
import './global.css';
import { ThemeProvider } from '@/components/theme-provider';
import { UserProvider } from '@auth0/nextjs-auth0/client'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <UserProvider>
        <body>
          <NavHeader></NavHeader>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </UserProvider>
    </html>
  )
}
